// <auto-generated />
using System;
using BlazorServer.StrategyPatternExample.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorServer.StrategyPatternExample.Migrations
{
    [DbContext(typeof(StrategyPatternContext))]
    partial class StrategyPatternContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.25");

            modelBuilder.Entity("BlazorServer.StrategyPatternExample.Domain.Models.ExportType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ExportTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "CSV",
                            IsActive = true,
                            Name = "CSV "
                        },
                        new
                        {
                            Id = 2,
                            Description = "Text",
                            IsActive = true,
                            Name = "TEXT "
                        },
                        new
                        {
                            Id = 3,
                            Description = "JSON",
                            IsActive = true,
                            Name = "JSON "
                        });
                });

            modelBuilder.Entity("BlazorServer.StrategyPatternExample.Domain.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "6 foot 3 inches",
                            IsActive = true,
                            Name = "Billy "
                        },
                        new
                        {
                            Id = 2,
                            Description = "6 foot 2 inches",
                            IsActive = true,
                            Name = "Fred "
                        },
                        new
                        {
                            Id = 3,
                            Description = "Blonde",
                            IsActive = true,
                            Name = "Bob "
                        },
                        new
                        {
                            Id = 4,
                            Description = "Bernet",
                            IsActive = true,
                            Name = "Jen "
                        },
                        new
                        {
                            Id = 5,
                            Description = "Skinny",
                            IsActive = true,
                            Name = "Penny "
                        },
                        new
                        {
                            Id = 6,
                            Description = "Pudgey",
                            IsActive = true,
                            Name = "Wilma "
                        },
                        new
                        {
                            Id = 7,
                            Description = "Nerd",
                            IsActive = true,
                            Name = "Todd "
                        },
                        new
                        {
                            Id = 8,
                            Description = "Jock",
                            IsActive = true,
                            Name = "Chad "
                        },
                        new
                        {
                            Id = 9,
                            Description = "Engineer",
                            IsActive = true,
                            Name = "Ellen "
                        },
                        new
                        {
                            Id = 10,
                            Description = "Poet",
                            IsActive = true,
                            Name = "Lou "
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
